---


- name: Update repos
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: Bulk dependency installation
  apt:
    pkg: "{{ item }}"
    state: present

  when: ansible_os_family == "Debian"
  with_items:
    - build-essential
    - python-dev
    - python
    - python-pip